version: '3.8'
services:
  frontend:
    image: weather-api-main-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    image: weather-api-main-backend
    ports:
      - "5000:5000"
    environment:
      - API_KEY=248d369aa6322178f4f2620b2da7f29c
